### ISSUE TITLE
Data to train

### ISSUE THREAD

**Issue by benjaminrobinet** [thangtran480/hair-segmentation#1]
Hello @thangtran480 
Your project seems to be very nice!
I've tried to train my own model there is no problem by using Figaro1K, but how did you use lfw images ?
Thanks :)

**Comment by juses0812** [comment]
Hi @thangtran480 & @benjaminrobinet , 
   Could you explain how to use Figaro 1K dataset?

**Comment by thangtran480** [comment]
Hi @benjaminrobinet 
I tried train my model on lfw dataset.  Its results are not good because many images in this dataset contain both hair and beard

**Comment by thangtran480** [comment]
Hi @juses0812 
you find data structure [here](https://github.com/thangtran480/hair-segmentation#data-structure)
