### ISSUE TITLE
How to apply color on Hair

### ISSUE THREAD

**Issue by technicalhunt** [thangtran480/hair-segmentation#12]
I downloaded the source code, but when I pick an image from the gallery it is taking too much time to respond, and the other thing is there is no option to add color to Hair, 
Please guide ...

**Comment by randauto** [comment]
app crash when I select picture from my photos. long time to respond.

**Comment by thangtran480** [comment]
Hi @technicalhunt  @randauto 
My application is in development, so it is still incomplete. You can use file .tflite to deploy your application.

**Comment by ductm104** [comment]
@technicalhunt This simple app only segment out the hair part and put a mask on it. To colorize, you have to write a pick color module and use color transfer algorithm. You can read more about color transfer [here](https://www.pyimagesearch.com/2014/06/30/super-fast-color-transfer-images/)
