### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by lbininhbl** [thangtran480/hair-segmentation#13]
Hi @thangtran480 
Every time I ran `python train.py`, I jus get the error "**ValueError: zero-size array to reduction operation maximum which has no identity**".

<img width="1565" alt="iShot2020-11-27 16 07 07" src="https://user-images.githubusercontent.com/5364138/100425726-ae41b180-30ca-11eb-800b-9a24ba040236.png">

Train all CelebAMask-HQ photos takes several hours, so I reduced the number of images to identify something wrong, but nothing. 

I made data struture like this:
![image](https://user-images.githubusercontent.com/5364138/100419880-63bb3780-30c0-11eb-9cd9-3869c66cf5fd.png)
![image](https://user-images.githubusercontent.com/5364138/100419897-6b7adc00-30c0-11eb-8786-909ecaae8dd7.png)

Are there any more steps I need to take?

**Comment by ductm104** [comment]
Did you debug your number of images, mask after load data from dir.

This error occurs when your image is empty.

**Comment by ductm104** [comment]
Maybe your number of samples is small than BATCH_SIZE, which default is 32. You can try BATCH_SIZE = 2
