### ISSUE TITLE
Android sample not work

### ISSUE THREAD

**Issue by narakai** [thangtran480/hair-segmentation#15]
After select an image app will hang and get an anr warning.

**Comment by thangtran480** [comment]
hi @narakai,

you can replace code [here](https://github.com/thangtran480/hair-segmentation/blob/bc145e89784cdfc4bfb30aaa178c612b61153060/HairApp/app/src/main/java/com/thangtv/hairapp/model/Segmentation.kt#L45) to `val options = Interpreter.Options()` to run application in android simulator
