### ISSUE TITLE
Deploy model to Android with Tensorflow Lite 

### ISSUE THREAD

**Issue by thangtran480** [thangtran480/hair-segmentation#4]

**Comment by thangtran480** [comment]
init app android

**Comment by thangtran480** [comment]
test a image
run-time: 0.3 in CPU Snapdragon 660

**Comment by akokhlik** [comment]
Hello,I am interested in your project, great job.But I have question.In android project how get Bitmap from output, I see You saved output into text file, but how can setPixel to bitmap

**Comment by thangtran480** [comment]
Hi @akokhlik, 
I wrote the code for the output as a mask. But I'm busy with another project, this project is interrupted
