### ISSUE TITLE
Use of multiple color

### ISSUE THREAD

**Issue by vidhishah22** [thangtran480/hair-segmentation#6]
Hello,

Thanks for sharing this. We found your code very useful. Is it possible to have a different color other than purple for hair? Where can I find the exact piece of code for the same?

Regards,
Vidhi

**Comment by thangtran480** [comment]
Hi @vidhishah22,
Thanks for your question

You can change color in  function transfer [here](https://github.com/thangtran480/hair-segmentation/blob/3626f214524e2edb1c37f495ebffbe5361d46823/demo.py#L23). You fix the values ​​in the _mask_ array to get the color you want
