### ISSUE TITLE
Models are missing

### ISSUE THREAD

**Issue by lrosique** [thangtran480/hair-segmentation#9]
Hi,

Thank you for your hard work, but in the commit of 
"add train model with GPU
@thangtran480
thangtran480 committed on 6 Jun"

you deleted the folder called models with its files, can you reupload them in the latest version please ? :)

**Comment by thangtran480** [comment]
HI @lrosique 
Thank you for visiting my repo
The model was saved in checkpoint folders. This folder contains the weight and history files that are saved after the training is completed
